dist: xenial
language: java
addons:
  apt:
    packages:
    - openjdk-7-jdk
jdk:
- openjdk7
- openjdk8
- openjdk11
branches:
  only:
  - develop
  - master
before_install:
- export TZ=Europe/Helsinki
install: true
script: mvn clean verify -q -Dgpg.skip
notifications:
  email:
    recipients:
    - andres.voll@nortal.com
    - aare.nurm@nortal.com
    - siim.suu@nortal.com
    on_success: change
    on_failure: always
